version: '2.12.1'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka'
    container_name: kafka
    ports:
      - '9092:9092'
    hostname: kafka
    links: 
     - zookeeper
    environment:
     - 'KAFKA_ADVERTISED_HOST_NAME=kafka'
     - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
     - KAFKA_ADVERTISED_PORT=9092

    






      